"""task types

Revision ID: bb74bdeefd5a
Revises: 1e1ee49d061c
Create Date: 2025-06-07 17:17:03.063085+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "bb74bdeefd5a"
down_revision: Union[str, None] = "1e1ee49d061c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("session_id", sa.UUID(), nullable=True))
    op.add_column("tasks", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "tasks", "sessions", ["session_id"], ["id"])
    op.create_foreign_key(None, "tasks", "users", ["user_id"], ["id"])
    op.sync_enum_values(
        enum_schema="public",
        enum_name="tasktypeenum",
        new_values=[
            "generate_course",
            "generate_user_summary",
            "generate_course_base",
            "generate_course_plan",
            "generate_module_plan",
            "generate_lesson_content_plan",
            "generate_content",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="tasks", column_name="task_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="tasktypeenum",
        new_values=[
            "generate_course",
            "generate_user_summary",
            "generate_course_plan",
            "generate_module_plan",
            "generate_lesson_plan",
            "generate_module",
            "generate_lesson",
            "generate_content",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="tasks", column_name="task_type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    op.drop_column("tasks", "session_id")
    # ### end Alembic commands ###
