"""tasks

Revision ID: 31476600b67e
Revises: 3d97c411ab35
Create Date: 2025-06-05 15:25:41.784387+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "31476600b67e"
down_revision: Union[str, None] = "3d97c411ab35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "pending", "in_progress", "success", "failed", name="taskstatusenum"
    ).create(op.get_bind())
    sa.Enum(
        "generate_course",
        "generate_user_summary",
        "generate_course_plan",
        "generate_module_plan",
        "generate_lesson_plan",
        "generate_module",
        "generate_lesson",
        "generate_content",
        name="tasktypeenum",
    ).create(op.get_bind())
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "task_type",
            postgresql.ENUM(
                "generate_course",
                "generate_user_summary",
                "generate_course_plan",
                "generate_module_plan",
                "generate_lesson_plan",
                "generate_module",
                "generate_lesson",
                "generate_content",
                name="tasktypeenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "in_progress",
                "success",
                "failed",
                name="taskstatusenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    sa.Enum(
        "generate_course",
        "generate_user_summary",
        "generate_course_plan",
        "generate_module_plan",
        "generate_lesson_plan",
        "generate_module",
        "generate_lesson",
        "generate_content",
        name="tasktypeenum",
    ).drop(op.get_bind())
    sa.Enum("pending", "in_progress", "success", "failed", name="taskstatusenum").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
