"""generate_type

Revision ID: 71c1e09ac4c2
Revises: 4cb4e4c7380b
Create Date: 2025-06-11 12:03:25.937495+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "71c1e09ac4c2"
down_revision: Union[str, None] = "4cb4e4c7380b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="tasktypeenum",
        new_values=[
            "generate_course",
            "generate_lesson",
            "generate_user_summary",
            "generate_course_base",
            "generate_course_plan",
            "generate_module_plan",
            "generate_lesson_content_plan",
            "generate_content",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="tasks", column_name="task_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="tasktypeenum",
        new_values=[
            "generate_course",
            "generate_user_summary",
            "generate_course_base",
            "generate_course_plan",
            "generate_module_plan",
            "generate_lesson_content_plan",
            "generate_content",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="tasks", column_name="task_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
