"""lesson content outline

Revision ID: 6841c21d8dfb
Revises: 203099c57107
Create Date: 2025-06-10 13:19:24.038198+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6841c21d8dfb"
down_revision: Union[str, None] = "203099c57107"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contents", sa.Column("outline", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contents", "outline")
    # ### end Alembic commands ###
