"""lesson_content

Revision ID: 7fbd77721eb9
Revises: b1da72150aac
Create Date: 2025-06-01 20:05:27.990916+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fbd77721eb9"
down_revision: Union[str, None] = "b1da72150aac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "TEXT",
        "VIDEO",
        "DIALOG",
        "OPEN_ANSWER",
        "REFLECTION",
        "TEST",
        name="content_type_enum",
    ).create(op.get_bind())
    op.create_table(
        "contents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "TEXT",
                "VIDEO",
                "DIALOG",
                "OPEN_ANSWER",
                "REFLECTION",
                "TEST",
                name="content_type_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("lessons", sa.Column("position", sa.Integer(), nullable=True))
    op.add_column("modules", sa.Column("position", sa.Integer(), nullable=True))
    op.execute("UPDATE lessons SET position = 0 WHERE position IS NULL")
    op.execute("UPDATE modules SET position = 0 WHERE position IS NULL")
    op.alter_column("lessons", "position", nullable=False)
    op.alter_column("modules", "position", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modules", "position")
    op.drop_column("lessons", "position")
    op.drop_table("contents")
    sa.Enum(
        "TEXT",
        "VIDEO",
        "DIALOG",
        "OPEN_ANSWER",
        "REFLECTION",
        "TEST",
        name="content_type_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
