"""add_role_user

Revision ID: 4cb4e4c7380b
Revises: 6841c21d8dfb
Create Date: 2025-06-10 19:00:22.379985+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4cb4e4c7380b"
down_revision: Union[str, None] = "6841c21d8dfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("USER", "ADMIN", name="user_role_enum").create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM("USER", "ADMIN", name="user_role_enum", create_type=False),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    sa.Enum("USER", "ADMIN", name="user_role_enum").drop(op.get_bind())
    # ### end Alembic commands ###
