"""add description and goals

Revision ID: 3d97c411ab35
Revises: c29c25ffc992
Create Date: 2025-06-03 21:48:04.162868+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "3d97c411ab35"
down_revision: Union[str, None] = "c29c25ffc992"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contents", sa.Column("description", sa.String(length=1000), nullable=True)
    )
    op.add_column("contents", sa.Column("goal", sa.String(length=1000), nullable=True))
    op.add_column("courses", sa.Column("goal", sa.String(length=1000), nullable=True))
    op.add_column("lessons", sa.Column("goal", sa.String(length=1000), nullable=True))
    op.add_column("modules", sa.Column("goal", sa.String(length=1000), nullable=True))
    op.sync_enum_values(
        enum_schema="public",
        enum_name="content_type_enum",
        new_values=[
            "TEXT",
            "VIDEO",
            "DIALOG",
            "PRACTICE",
            "EXAMPLES",
            "MISTAKES",
            "REFLECTION",
            "TEST",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="contents", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="content_type_enum",
        new_values=["TEXT", "VIDEO", "DIALOG", "OPEN_ANSWER", "REFLECTION", "TEST"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="contents", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("modules", "goal")
    op.drop_column("lessons", "goal")
    op.drop_column("courses", "goal")
    op.drop_column("contents", "goal")
    op.drop_column("contents", "description")
    # ### end Alembic commands ###
