"""оптимизировал модели и связи с session

Revision ID: 8584f51fdfa3
Revises: f5ab0c7f4ddc
Create Date: 2025-05-31 10:19:01.015480+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8584f51fdfa3"
down_revision: Union[str, None] = "f5ab0c7f4ddc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("sessions_user_id_fkey"), "sessions", type_="foreignkey")
    op.drop_column("sessions", "user_id")
    op.drop_constraint(op.f("users_session_id_fkey"), "users", type_="foreignkey")
    op.drop_column("users", "session_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("users_session_id_fkey"), "users", "sessions", ["session_id"], ["id"]
    )
    op.add_column(
        "sessions", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("sessions_user_id_fkey"), "sessions", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
