"""session in course and pref

Revision ID: 1fdb516473f8
Revises: ea078a748db3
Create Date: 2025-05-31 08:31:59.959404+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fdb516473f8"
down_revision: Union[str, None] = "ea078a748db3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("session_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "courses", "sessions", ["session_id"], ["id"])
    op.add_column("preferences", sa.Column("session_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "preferences", "sessions", ["session_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "preferences", type_="foreignkey")
    op.drop_column("preferences", "session_id")
    op.drop_constraint(None, "courses", type_="foreignkey")
    op.drop_column("courses", "session_id")
    # ### end Alembic commands ###
