"""session_unique

Revision ID: 1e1ee49d061c
Revises: 31476600b67e
Create Date: 2025-06-06 17:27:55.408303+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e1ee49d061c"
down_revision: Union[str, None] = "31476600b67e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_ip_user_agent", "sessions", ["ip", "user_agent"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_ip_user_agent", "sessions", type_="unique")
    # ### end Alembic commands ###
