"""add_email_password

Revision ID: 09b46557feaa
Revises: d3acc0b2e1a1
Create Date: 2025-05-27 19:08:31.218185+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09b46557feaa"
down_revision: Union[str, None] = "d3acc0b2e1a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=256), nullable=False))
    op.add_column("users", sa.Column("email", sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
