"""удалил example и mistakes

Revision ID: a191f2dcf248
Revises: 71c1e09ac4c2
Create Date: 2025-06-11 19:25:52.554620+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "a191f2dcf248"
down_revision: Union[str, None] = "71c1e09ac4c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="content_type_enum",
        new_values=[
            "TEXT",
            "VIDEO",
            "DIALOG",
            "PRACTICE",
            "REFLECTION",
            "TEST",
            "CODE",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="contents", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="content_type_enum",
        new_values=[
            "TEXT",
            "VIDEO",
            "DIALOG",
            "PRACTICE",
            "EXAMPLES",
            "MISTAKES",
            "REFLECTION",
            "TEST",
            "CODE",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="contents", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
