"""delete ip, user_agent

Revision ID: a360f25e6246
Revises: a191f2dcf248
Create Date: 2025-06-14 20:29:06.350913+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a360f25e6246"
down_revision: Union[str, None] = "a191f2dcf248"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_ip_user_agent"), "sessions", type_="unique")
    op.drop_column("sessions", "user_agent")
    op.drop_column("sessions", "ip")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column("ip", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "user_agent", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint(
        op.f("uq_ip_user_agent"),
        "sessions",
        ["ip", "user_agent"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
