"""preference__summary

Revision ID: f5ab0c7f4ddc
Revises: 1fdb516473f8
Create Date: 2025-05-31 09:47:50.918304+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5ab0c7f4ddc"
down_revision: Union[str, None] = "1fdb516473f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("preferences", sa.Column("summary", sa.Text(), nullable=True))
    op.drop_column("preferences", "profile_summary")
    op.add_column("sessions", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "sessions", "users", ["user_id"], ["id"])
    op.add_column("users", sa.Column("session_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "users", "sessions", ["session_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "session_id")
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_column("sessions", "user_id")
    op.add_column(
        "preferences",
        sa.Column("profile_summary", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("preferences", "summary")
    # ### end Alembic commands ###
