"""null preference

Revision ID: 6006ac883cfa
Revises: 8584f51fdfa3
Create Date: 2025-05-31 10:23:42.066097+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6006ac883cfa"
down_revision: Union[str, None] = "8584f51fdfa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("preferences", "user_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("preferences", "course_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("preferences", "course_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("preferences", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
